version: '3.8'

services:
    example-backend:
      image: example-backend
      ports:
        - 8080:8080
      command: "./server"
      environment:
        - PORT=8080
        - REQUEST_ORIGIN=http://localhost:5000
    example-frontend:
      image: example-frontend
      environment:
      - BACKEND_URL=http://localhost:8080
      command: ["serve", "-s", "-l", "5000", "build"]
      ports:
        - 5000:5000